#!/bin/bash

# MySQL user
user=root
# MySQL password
password=admin

SCRIPT_PATH=`readlink -f "$0"`
SCRIPT_DIR=`dirname "$SCRIPT_PATH"`

# Backup storage directory 
backupfolder="${SCRIPT_DIR}/database/backups"
# backupfolder=/var/www/html/database/backups

sqlfile=$backupfolder/events-$(date +%Y-%m-%d_%H:%M:%S).sql
# Create a backup 
mysqldump -u $user -p$password events > $sqlfile 

echo $sqlfile